config/routes.rb
SampleApp::Application.routes.draw do  

  get '/pages/index' => redirect('/pages')
  
  resources :sessions, :only => [:new, :create, :destroy] do 
    collection do
      get :fb_signin
    end
  end
  
  resources :users do
    member do
      get :following, :followers       #makes users/1/following and following_user_path
      delete :unlink_provider
      get :provider_id
    end
    collection do
      post :send_password_recovery
      get :password_recovery
      get :activate
      get :send_activation
      post :create_fb
      get :new_fb
    end
  end

  resources :pages

  resources :tokens, :only => [:create, :destroy] do
    collection do
      put :refresh
      get :logout, to: 'tokens#destroy'
      post :external_auth
      get :web_external_auth
    end
  end

  resources :spots do
    resources :comments
    resources :ratings
  end

  resources :comments do
    resources :ratings
  end

  resources :ratings
  resources :comments
  resources :relationships, :only => [:create, :destroy]

  get '/auth/facebook/callback', :to => 'sessions#fb_signin'

  put '/users/:user_id/questions/:question_id/ratings', to: 'ratings#update'
  post '/users/:user_id/questions/:question_id/ratings', to: 'ratings#create'
  delete '/users/:user_id/questions/:question_id/ratings', to: 'ratings#destroy'

  post '/questions/:question_id/relationships', to: 'relationships#create'
  delete '/questions/:question_id/relationships', to: 'relationships#destroy'
  get '/questions/:question_id/relationships', to: 'relationships#show'
  get '/users/:user_id/favorites', to: 'questions#favorites'

  root :to => "pages#home" 
  get '/signup', :to => 'users#new'
  get '/contact', :to => 'pages#contact'
  get '/about', :to => 'pages#about'
  get '/signin', :to => 'sessions#new'
  get '/signout', :to => 'sessions#destroy'
  get '/admin', :to => 'pages#admin'
  get '/maintenance', :to => 'pages#maintenance'
  get '/error', :to => 'pages#error'
  get '/sitemap', :to => 'pages#site_map'
  get '/sitemap_xml', :to => 'pages#site_map_xml'

end

app/models/question.rb
class Question < ActiveRecord::Base

  attr_protected

  has_many :answers, :through => :response_options

  #complex relationship to comments
  has_many :comments, -> { where target_type: RELATIONSHIP_TYPE_QUESTION},
           :dependent => :destroy,
           :foreign_key => "target_id",
           :class_name => "Comment"

  has_many :ratings, -> { where target_type: RELATIONSHIP_TYPE_QUESTION},
           :dependent => :destroy,
           :foreign_key => "target_id"

  #complex favorites relationships
  has_many :user_relationships, -> { where target_type: RELATIONSHIP_TYPE_QUESTION},
           :dependent => :destroy,
           :foreign_key => "target_id",
           :class_name => "Relationship"
  has_many :followers, :through => :user_relationships, :source => :follower

  #serialization, add methods
  def serializable_hash(options={})
    options[:methods] ||= :rating_score

    result =  super
    result[:is_user_favorite] = self.is_user_favorite options[:user_id] if options[:user_id]
    result
  end

  def rating_score
    ratings.sum(:value)
  end

  def is_user_favorite user_id

    fav = nil

    if user_id
      fav = Relationship.find_by :target_type => RELATIONSHIP_TYPE_QUESTION, :user_id => user_id, :target_id => self.id
    end

   fav != nil
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_filter :admin_user, :only => [:new, :create, :edit, :update, :destroy]

  def new
    @object = Question.new
  end

  def create
    @object = Question.new(get_request_as_json params, :question)

    if @object.save

      respond_to do |format|
        format.html  {redirect_to @object}
        format.json  { render :json => @object }
      end

    else
      respond_to do |format|
        format.html  {render 'new'}
        format.json  { render :json => {:result => "Error"} }
      end
    end
  end

  def show
    @title = 'Details'
    id = params[:id]
    @object = Question.find(id)

    respond_to do |format|
      format.html  #normal flow
      format.json  { render :json => @object, :include => [{:comments => {:include => :user}}, :ratings,], :user_id => current_user_id }
    end

  end

  def edit
    @title = "Edit"
    @object = Question.find(id = params[:id])

    respond_to do |format|
      format.html  #normal flow
      format.json  { render :json => @object }
    end
  end

  def update
    @object = Question.find(params[:id])

    if @object.update_attributes(get_request_as_json params, :question)

      respond_to do |format|
        format.html  {redirect_to @object}
        format.json  { render :json => @object }
      end

    else
      respond_to do |format|
        format.html  {render 'edit'}
        format.json  { render :json => {:result => "Error"} }
      end
    end
  end

  def index

    @objects = Question.all

    respond_to do |format|
      format.html  #normal flow
      format.json  {render :json => @objects, :include => [{:comments => {:include => :user}}, ], :user_id => current_user_id}
    end
  end

  def favorites
    @objects = current_user.favorite_questions

    respond_to do |format|
      format.html  #normal flow
      format.json  {render :json => @objects, :include => [{:comments => {:include => :user}}], :user_id => current_user_id }
    end

  end

  def destroy
    object = Question.find(params[:id])

    object.destroy

    respond_to do |format|
      format.html  {redirect_to questions_path, :flash => {:success => "Object Deleted"}}
      format.json  {render :json => {:result => "success"}}
    end
  end

end

app/views/questions/_object.html.erb
<li>
	<%= link_to object.name, object %>

</li>

app/views/questions/edit.html.erb
<h1>Edit Object</h1>

<%= form_for(@object) do |f| %>
                            
<!-- the argument :f below is to pass the f into the partial -->
<%= render 'fields', :f => f%>

<div class="actions">
  <%= f.submit "Update", :class => "btn btn-primary"%>
</div>

<% end %>

</div>

app/views/questions/index.html.erb
<h1>All</h1>

<%if current_user and current_user.admin %>
  <%= link_to "Add New", new_question_path %>
<% end %>
      

<ul class="index">

  <% @objects.each do |object| %>
      <%=render 'object', :object => object %>
  <%end%>

</ul> 

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= form_for(@object) do |f| %>

<%= render 'fields', :f => f %>  

<div class="actions">
  <%= f.submit "Create", :class => "btn btn-primary"%>
</div>

<% end %>

app/views/questions/show.html.erb
  <div>
    <% if current_user and current_user.admin %>
         <%= link_to "Edit", edit_question_path(@object) %>

        <% if current_user and current_user.admin? %>
            | <%= link_to "delete", @object, :method => :delete, :data => { :confirm => "Are you sure?"},
                          :title => "Delete #{@object.name}"%>
        <%end%>
    <% end %>

    <h1><strong><%= @object.name%></strong></h1>
    <h3><%=@object.text %></h3>

    <strong>Comments
        <%= link_to "+", new_question_comment_path(@object) %>
    </strong>
    <% @object.comments.each do |comment| %>
        <%= render "comments/object", :object => comment %>
    <% end %>

    <div>
    <strong>Ratings
      <%= link_to "+", new_question_rating_path(@object) %>
    </strong>
    ( <%= @object.ratings.count %> )
    </div>

    <p><%=render "relationships/follow_button", :target_id => @object.id, :target_type => RELATIONSHIP_TYPE_QUESTION %></p>


  </div>