config/routes.rb
SampleApp::Application.routes.draw do  

  get '/pages/index' => redirect('/pages')
  
  resources :sessions, :only => [:new, :create, :destroy] do 
    collection do
      get :fb_signin
    end
  end
  
  resources :users do
    member do
      get :following, :followers       #makes users/1/following and following_user_path
      delete :unlink_provider
      get :provider_id
    end
    collection do
      post :send_password_recovery
      get :password_recovery
      get :activate
      get :send_activation
      post :create_fb
      get :new_fb
    end
  end

  resources :pages

  resources :tokens, :only => [:create, :destroy] do
    collection do
      put :refresh
      get :logout, to: 'tokens#destroy'
      post :external_auth
      get :web_external_auth
    end
  end

  resources :spots do
    resources :comments
    resources :ratings
  end

  resources :comments do
    resources :ratings
  end

  resources :ratings
  resources :comments
  resources :relationships, :only => [:create, :destroy]

  get '/auth/facebook/callback', :to => 'sessions#fb_signin'

  put '/users/:user_id/questions/:question_id/ratings', to: 'ratings#update'
  post '/users/:user_id/questions/:question_id/ratings', to: 'ratings#create'
  delete '/users/:user_id/questions/:question_id/ratings', to: 'ratings#destroy'

  post '/questions/:question_id/relationships', to: 'relationships#create'
  delete '/questions/:question_id/relationships', to: 'relationships#destroy'
  get '/questions/:question_id/relationships', to: 'relationships#show'
  get '/users/:user_id/favorites', to: 'questions#favorites'

  root :to => "pages#home" 
  get '/signup', :to => 'users#new'
  get '/contact', :to => 'pages#contact'
  get '/about', :to => 'pages#about'
  get '/signin', :to => 'sessions#new'
  get '/signout', :to => 'sessions#destroy'
  get '/admin', :to => 'pages#admin'
  get '/maintenance', :to => 'pages#maintenance'
  get '/error', :to => 'pages#error'
  get '/sitemap', :to => 'pages#site_map'
  get '/sitemap_xml', :to => 'pages#site_map_xml'

end

app/views/pages/_content.html.erb
<% if page != nil %>
<div class="page_content">
  <%= page.content.html_safe %>
</div>
<% end %>

app/views/pages/_fields.html.erb
<%= render 'shared/error_messages', :object => f.object %>   

<script src="http://js.nicedit.com/nicEdit-latest.js" type="text/javascript"></script>
<script type="text/javascript">
    bkLib.onDomLoaded(function() {
           new nicEditor().panelInstance('content');
    });
</script>

<div class="field">
  <%= f.label :title%> <br/>
  <%= f.text_field :title%>
</div>     

<div class="field">
  <%= f.label :content%>
  <%= f.text_area :content, :cols => 80, :rows => 25, :id => "content", :class => "full_width_percent"%>
</div>

app/views/pages/_object.html.erb
<li>
	<%= link_to object.title, object %>
	
	<% if current_user and current_user.admin? %>
	| <%= link_to "delete", object, :method => :delete, :data => { :confirm => "Are you sure?"},
									:title => "Delete #{object.title}"%>
	<%end%>
	   
</li>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>This is a basic Ruby on Rails starting project. Expand it to add new stuff!</p>

app/views/pages/admin.html.erb
<div class="well">
  <h3>Admin Links</h3>
  <p><%= link_to 'Pages', pages_path %>  </p>
  <p><%= link_to 'Users', users_path %>  </p>
  <p><%= link_to 'Questions', questions_path %>  </p>
</div>




<div class="well">
    <h3>Stats</h3>
    <p><strong>Users:</strong> <%= @user_count %></p>
</div>

app/views/pages/contact.html.erb
<h1>Contact Us</h1>
<p>logan@gmail.com</p>

app/views/pages/edit.html.erb
<h1>Edit Page</h1>

<%= form_for(@object) do |f| %>
                            
<!-- the argument :f below is to pass the f into the partial -->
<%= render 'fields', :f => f%>

<div class="actions">
  <%= f.submit "Update"%>
</div>

<% end %> 

app/views/pages/error.html.erb
There was an error viewing the page you requested.

app/views/pages/home.html.erb
<% if signed_in?%>
    <p>We are currently in development. Pardon the mess.</p>
	<table class="front" summary="for signed in users">
		   <tr>

			<td class="sidebar round">
				<%= render "shared/sidebar_shared"%>
			</td>
		   </tr>
	</table>

<% else %>


<p>We are currently in development. Pardon the mess.</p>

<%= link_to "Sign up now!", signup_path, :class => "signup_button round"%>      

<% end %>

app/views/pages/index.html.erb
<h1>All</h1>

<%if current_user and current_user.admin %>
  <%= link_to "Add New", new_page_path %>
<% end %>

<ul class="index">

  <% @pages.each do |object| %>
      <%=render 'object', :object => object %>
  <%end%>

</ul>

app/views/pages/maintenance.html.erb
<%= CONSTANTS[  :app_name]%> is currently down for maintenance.

app/views/pages/new.html.erb
<h1>New Page</h1>

<%= form_for(@object) do |f| %>

<%= render 'fields', :f => f %>  

<div class="actions">
  <%= f.submit "Create"%>
</div>

<% end %>

app/views/pages/show.html.erb
  <% if current_user and current_user.admin %>
     <%= link_to "Edit", edit_page_path(@object) %>
  <% end %>

  <div class="page_content">
    <%= @object.content.html_safe if @object and !@object.content.blank? %>
  </div>

app/views/pages/site_map_xml.html.erb
<url>
<loc><%= pages_url %></loc>
<lastmod><%= @pages.last.updated_at %> </lastmod>
<changefreq>monthly </changefreq>
<priority>1 </priority>
</url>

<% @pages.each do |object| %>
    <url>
    <loc><%= page_url(object) %></loc>
    <lastmod><%= object.updated_at %> </lastmod>
    <changefreq>monthly </changefreq>
    <priority>1 </priority>
    </url>
<% end %>