config/routes.rb
SampleApp::Application.routes.draw do  

  get '/pages/index' => redirect('/pages')
  
  resources :sessions, :only => [:new, :create, :destroy] do 
    collection do
      get :fb_signin
    end
  end
  
  resources :users do
    member do
      get :following, :followers       #makes users/1/following and following_user_path
      delete :unlink_provider
      get :provider_id
    end
    collection do
      post :send_password_recovery
      get :password_recovery
      get :activate
      get :send_activation
      post :create_fb
      get :new_fb
    end
  end

  resources :pages

  resources :tokens, :only => [:create, :destroy] do
    collection do
      put :refresh
      get :logout, to: 'tokens#destroy'
      post :external_auth
      get :web_external_auth
    end
  end

  resources :spots do
    resources :comments
    resources :ratings
  end

  resources :comments do
    resources :ratings
  end

  resources :ratings
  resources :comments
  resources :relationships, :only => [:create, :destroy]

  get '/auth/facebook/callback', :to => 'sessions#fb_signin'

  put '/users/:user_id/questions/:question_id/ratings', to: 'ratings#update'
  post '/users/:user_id/questions/:question_id/ratings', to: 'ratings#create'
  delete '/users/:user_id/questions/:question_id/ratings', to: 'ratings#destroy'

  post '/questions/:question_id/relationships', to: 'relationships#create'
  delete '/questions/:question_id/relationships', to: 'relationships#destroy'
  get '/questions/:question_id/relationships', to: 'relationships#show'
  get '/users/:user_id/favorites', to: 'questions#favorites'

  root :to => "pages#home" 
  get '/signup', :to => 'users#new'
  get '/contact', :to => 'pages#contact'
  get '/about', :to => 'pages#about'
  get '/signin', :to => 'sessions#new'
  get '/signout', :to => 'sessions#destroy'
  get '/admin', :to => 'pages#admin'
  get '/maintenance', :to => 'pages#maintenance'
  get '/error', :to => 'pages#error'
  get '/sitemap', :to => 'pages#site_map'
  get '/sitemap_xml', :to => 'pages#site_map_xml'

end

app/views/layouts/_analytics.html.erb
<!-- Google Analytics -->
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', '<%= CONSTANTS[  :google_analytics_id] %>', 'auto');
    ga('send', 'pageview');

</script>
<!-- End Google Analytics -->

app/views/layouts/_footer.html.erb
<div id="footer" class="navbar-inverse" role="navigation">
  <nav class="footer-nav">
    <ul>
      <li><%= link_to "About", about_path %></li>
 			<li><%= link_to "Contact", contact_path %></li>
 			<li><%= link_to "News", '#'%></li>
    </ul>
  </nav>
  <p class="copyright">Copyright &copy; 2014 <%= CONSTANTS[  :app_name] %>. All rights reserved.</p>
  <%= link_to 'site map', "/sitemap", :class => "copyright"%>
  <%= link_to 'xml site map', "/sitemap_xml", :class => "copyright"%>
</div>
	   

app/views/layouts/_head.html.erb
<% if @object and @object.respond_to? :meta_title and @object.meta_title %>
    <title><%= @object.meta_title %></title>
<% else %>
    <title><%= CONSTANTS[  :app_name] %> </title>
<% end %>

<% if @object and @object.respond_to? :meta_description and @object.meta_description %>
    <meta name="description" content=" <%= @object.meta_description %>">
<% else %>
    <meta name="description" content="<%=CONSTANTS[  :app_description]%>">
<%end %>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= csrf_meta_tag %>

    <!-- BootStrap -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>



    <!--[if lt IE 9]>
        <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"/>
    <![endif]-->


    <% if Rails.env.production? %>
        <%= render "layouts/analytics" %>

    <% end %>

<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
<link rel="icon" href="/favicon.ico" type="image/x-icon">

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag(CONSTANTS[:header_image], alt: "App Home", :height => 50), root_path %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
         <% if signed_in?  %>
        	<li><%= link_to "My Profile", user_path(current_user) %></li>
        	<li><%= link_to "Settings", edit_user_path(current_user) %></li>
         <%end%>

         <% if signed_in? and current_user.admin? %>
             <li><%= link_to "Admin", "/admin" %></li>
         <% end %>

         <li><%= link_to "Help", page_path(:id => "help") %></li>
         <% if signed_in?  %>
        	<li><%= link_to "Sign out", signout_path %></li>
         <% else%>
        	<li><%= link_to "Sign in", signin_path %></li>
        	<li><%= render "users/fb_link"%> </li>
         <% end%>
       </ul>
    </div>
   </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <%= render "layouts/head" %>

</head>
	
<body>

    <div id="wrap">
     <%= render 'layouts/header'  %>

    <div class="container">

		<section class="round">
			<% flash.each do |key,value|%>
			 	<div class="flash <%= key %>">
				    <%= value %>
				</div>
			<%end%>

        </section>

		<%= yield %>
    </div>
  </div>
		<%= render 'layouts/footer'  %>

</body>
</html>